; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
# default_envs = nodemcu-32s
default_envs = esp32-s3-devkitc-1

[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = espidf
monitor_speed = 115200
build_flags =
    -DLED_GREEN_GPIO=GPIO_NUM_25
    -DLED_YELLOW_GPIO=GPIO_NUM_26
    -DLED_RED_GPIO=GPIO_NUM_27

[env:esp32-s3-devkitc-1]
platform = espressif32
# board = esp32s3box
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
build_flags =
    -DLED_GREEN_GPIO=GPIO_NUM_4
    -DLED_YELLOW_GPIO=GPIO_NUM_5
    -DLED_RED_GPIO=GPIO_NUM_6
    -DONBOARD_LED_ENABLED=1
    -DONBOARD_LED_GPIO=GPIO_NUM_48
