; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = nodemcu-32s
# default_envs = freenove_esp32_s3_wroom

[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = espidf
monitor_speed = 115200
build_flags =
    -DLED_GREEN_GPIO=GPIO_NUM_25
    -DLED_YELLOW_GPIO=GPIO_NUM_26
    -DLED_RED_GPIO=GPIO_NUM_27

[env:freenove_esp32_s3_wroom]
platform = espressif32
board = freenove_esp32_s3_wroom
framework = espidf
monitor_speed = 115200
build_flags =
    -DLED_GREEN_GPIO=GPIO_NUM_1
    -DLED_YELLOW_GPIO=GPIO_NUM_2
    -DLED_RED_GPIO=GPIO_NUM_3
